version: '3'

services:
  generator:
    build: ./generator
    container_name: generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000


  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      PUBLISH_TOPIC: streaming.transactions.publish


networks:
  default:
    external:
      name: kafka-network
